const namesOfJobs = [
  { title: "Software Developer" },
  { title: "Data Engineer" },
  { title: "Data Scientist" },
  { title: "Systems Analyst" },
  { title: "Project Manager" },
  { title: "Solutions Architect" },
  { title: "Network Administrator" },
  { title: "Network Engineer" },
  { title: "Technical Support Analyst" },
  { title: "Graphic Designer" },
  { title: "UX/UI Designer" },
  { title: "Information Security Engineer" },
  { title: "Database Administrator" },
  { title: "Digital Marketing Specialist" },
  { title: "IT Consultant" },
  { title: "Game Developer" },
  { title: "Embedded Software Engineer" },
  { title: "Web Developer" },
  { title: "Mobile Application Developer" },
  { title: "DevOps Engineer" },
  { title: "Quality Assurance (QA) Analyst" },
  { title: "Business Analyst" },
  { title: "Machine Learning Engineer" },
  { title: "Artificial Intelligence Specialist" },
  { title: "Systems Administrator" },
  { title: "Cloud Architect" },
  { title: "Full Stack Developer" },
  { title: "Front-end Developer" },
  { title: "Back-end Developer" },
  { title: "Information Security Analyst" },
  { title: "General Practitioner (GP)" },
  { title: "Nurse" },
  { title: "Physiotherapist" },
  { title: "Dentist" },
  { title: "Pharmacist" },
  { title: "Psychologist" },
  { title: "Nutritionist" },
  { title: "Nursing Technician" },
  { title: "Radiologist" },
  { title: "Speech Therapist" },
  { title: "Civil Engineer" },
  { title: "Mechanical Engineer" },
  { title: "Architect" },
  { title: "Urban Planner" },
  { title: "Electrical Engineer" },
  { title: "Environmental Engineer" },
  { title: "Truck Driver" },
  { title: "Airline Pilot" },
  { title: "Heavy Machinery Operator" },
  { title: "Public Transport Driver" },
  { title: "Logistics Analyst" },
  { title: "Sales Manager" },
  { title: "Sales Representative" },
  { title: "Customer Service Specialist" },
  { title: "Marketing Coordinator" },
  { title: "Marketing Analyst" },
  { title: "Social Media Manager" },
  { title: "Sales Consultant" },
  { title: "Administrative Assistant" },
  { title: "Financial Analyst" },
];

export { namesOfJobs };
