const namesOfJobs = [
  "Software Developer",
  "Data Engineer",
  "Data Scientist",
  "Systems Analyst",
  "Project Manager",
  "Solutions Architect",
  "Network Administrator",
  "Network Engineer",
  "Technical Support Analyst",
  "Graphic Designer",
  "UX/UI Designer",
  "Information Security Engineer",
  "Database Administrator",
  "Digital Marketing Specialist",
  "IT Consultant",
  "Game Developer",
  "Embedded Software Engineer",
  "Web Developer",
  "Mobile Application Developer",
  "DevOps Engineer",
  "Quality Assurance (QA) Analyst",
  "Business Analyst",
  "Machine Learning Engineer",
  "Artificial Intelligence Specialist",
  "Systems Administrator",
  "Cloud Architect",
  "Full Stack Developer",
  "Front-end Developer",
  "Back-end Developer",
  "Information Security Analyst",
  "General Practitioner (GP)",
  "Nurse",
  "Physiotherapist",
  "Dentist",
  "Pharmacist",
  "Psychologist",
  "Nutritionist",
  "Nursing Technician",
  "Radiologist",
  "Speech Therapist",
  "Civil Engineer",
  "Mechanical Engineer",
  "Architect",
  "Urban Planner",
  "Electrical Engineer",
  "Environmental Engineer",
  "Truck Driver",
  "Airline Pilot",
  "Heavy Machinery Operator",
  "Public Transport Driver",
  "Logistics Analyst",
  "Sales Manager",
  "Sales Representative",
  "Customer Service Specialist",
  "Marketing Coordinator",
  "Marketing Analyst",
  "Social Media Manager",
  "Sales Consultant",
  "Administrative Assistant",
  "Financial Analyst",
];

export { namesOfJobs };
